version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
before_build:
- ps: nuget restore src\ChallengeDev.sln -DisableParallelProcessing -Verbosity quiet
build:
  verbosity: minimal
